### ISSUE TITLE
🔻fix-결제 페이지 디자인 전체 수정

### ISSUE THREAD

**Issue by sujinyang00** [TEAMMatchDev/FrontEnd_Match_REACT#210]
## 🛠️기능 설명 or 브랜치 생성 목적
> 설명 적어 주세용

## ✅To-do list🗒️
- [x] 카드 등록 버튼 이미지 교체
- [ ] 상단에 기부 진행 상태바 추가
- [ ] CardCarousel 위치 중앙으로
- [x] 결제동의 아이콘 actice & unactive 수정
- [x] 다음버튼 색 #1D1F23 변경
- [ ] 이전버튼 추가
- [ ] 화면 텍스트 정보 수정
- [ ] 후순위) 안내사항 CardCarousel 내부로 이동
- [ ] 후순위) CardCaoursel 내부 안내멘트 추가
